export const API_URL = 'http://192.168.5.108:8123';
export const TIME_OUT = 2000;
export const INPUT_TYPE = 'standard';
export const ERROR_MSG = 'Comuníquese con el administrador del sistema';
export const PAGE_SIZE = 50;  
export const ID_PROGRAMS = 163119;
export const ID_STATES = 2;
export const ID_PERIODS = 1;
export const ID_REFERRED_STATUS = 6;